=== Espinetius/dawGit/1 Daw/Lenguaje de marcas ejerccios/xml/notasMejorado.dtd
<!ELEMENT SSOO (teoria,practica)>
<!ELEMENT teoria (alumno+)>
<!ELEMENT alumno (matricula,nombre,apellido,notaTeoria?,notaPractica?)>
<!ATTLIST alumno id NMTOKEN #REQUIRED>
<!ELEMENT matricula (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT notaTeoria (#PCDATA)>
<!ELEMENT practica (alumno+)>
<!ELEMENT notaPractica (#PCDATA)>

=== Espinetius/dawGit/1 Daw/Lenguaje de marcas ejerccios/xml/notasMejorado.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SSOO SYSTEM "notasMejorado.dtd">
<SSOO>
    <teoria>
        <alumno id="1">
            <matricula>123456789</matricula>
            <nombre>pepe</nombre>
            <apellido>pepito</apellido>
            <notaTeoria>10</notaTeoria>
        </alumno>
        <alumno id="2">
            <matricula>987654321</matricula>
            <nombre>Jose</nombre>
            <apellido>josecito</apellido>
            <notaTeoria>8</notaTeoria>
        </alumno>
        <alumno id="3">
            <matricula>654987321</matricula>
            <nombre>Maria</nombre>
            <apellido>unchaletenelcampo</apellido>
            <notaTeoria>9</notaTeoria>
        </alumno>
        <alumno id="4">
            <matricula>456789123</matricula>
            <nombre>Manuela</nombre>
            <apellido>manolita</apellido>
            <notaTeoria>5</notaTeoria>
        </alumno>
    </teoria>
    <practica>
        <alumno id="1">
            <matricula>123456789</matricula>
            <nombre>pepe</nombre>
            <apellido>pepito</apellido>
            <notaPractica>10</notaPractica>
        </alumno>
        <alumno id="2">
            <matricula>987654321</matricula>
            <nombre>Jose</nombre>
            <apellido>josecito</apellido>
            <notaPractica>6</notaPractica>
        </alumno>
        <alumno id="3">
            <matricula>654987321</matricula>
            <nombre>Maria</nombre>
            <apellido>unchaletenelcampo</apellido>
            <notaPractica>7</notaPractica>
        </alumno>
        <alumno id="4">
            <matricula>456789123</matricula>
            <nombre>Manuela</nombre>
            <apellido>manolita</apellido>
            <notaPractica>8</notaPractica>
        </alumno>
    </practica>
</SSOO>
