=== Espinetius/dawGit/1 Daw/Lenguaje de marcas ejerccios/xml/tiendaAnimales.dtd
<!ELEMENT animal (perro)>
<!ELEMENT perro (nombre,raza,fechNac,sexo,codperro,madPerro,padPerro,veterinario)>
<!ATTLIST perro id NMTOKEN #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT raza (#PCDATA)>
<!ELEMENT fechNac (#PCDATA)>
<!ATTLIST fechNac fech CDATA #REQUIRED>
<!ELEMENT sexo (#PCDATA)>
<!ATTLIST sexo sex CDATA #REQUIRED>
<!ELEMENT codperro (#PCDATA)>
<!ELEMENT madPerro (#PCDATA)>
<!ELEMENT padPerro (#PCDATA)>
<!ELEMENT veterinario (#PCDATA)>

=== Espinetius/dawGit/1 Daw/Lenguaje de marcas ejerccios/xml/tiendaAnimales.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE animal SYSTEM "tiendaAnimales.dtd">
<animal>
    <perro id="1">
        <nombre>lua</nombre>
        <raza>Alaska</raza>
        <fechNac fech="12/06/2022">12/06/2022</fechNac>
        <sexo sex="?">hembra</sexo>
        <codperro>1234</codperro>
        <madPerro>tina</madPerro>
        <padPerro>toby</padPerro>
        <veterinario>Antonio Garcia Paredes</veterinario>
    </perro>
</animal>
